### ISSUE TITLE
AttributeError: 'Conv2DLayer' object has no attribute 'num_groups'

### ISSUE THREAD

**Issue by enniyasubbu** [kahst/AcousticEventDetection#4]
Theano - v1.0.1
Lasagne - v0.2.dev1

Command:
`python AED_test.py --filenames 'dataset/schreien_scream.wav' --modelname 'AED_Example_Run_model.pkl' --overlap 4 --results 5 --confidence 0.01`

```
HANDLING IMPORTS...
Using cuDNN version 7103 on context None
Mapped name None to device cuda: GeForce GT 650M (0000:01:00.0)
...DONE!
IMPORTING MODEL... DONE!
Traceback (most recent call last):
  File "AED_test.py", line 159, in <module>
    TEST_NET = getPredictionFuntion(NET)
  File "AED_test.py", line 71, in getPredictionFuntion
    net_output = l.get_output(net, deterministic=True)
  File "/home/enniya/miniconda2/lib/python2.7/site-packages/lasagne/layers/helper.py", line 197, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/home/enniya/miniconda2/lib/python2.7/site-packages/lasagne/layers/conv.py", line 352, in get_output_for
    conved = self.convolve(input, **kwargs)
  File "/home/enniya/miniconda2/lib/python2.7/site-packages/lasagne/layers/conv.py", line 643, in convolve
    if self.num_groups > 1:  # pragma: no cover
AttributeError: 'Conv2DLayer' object has no attribute 'num_groups'
```

**Comment by kahst** [comment]
The reason for this the newest Lasagne release. `num_groups` is a new feature to the `Conv2DLayer`, unfortunately the downloadable snapshot of the net does not support this feature. There's only two options here: Use an older Lasagne version (which might not work well with the newest Theano release) or train your own model and use that snapshot instead.
